name: Build and Stop Docker Compose

on:
  push:
    branches:
      - main
      
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Start containers
      run: |
        cd ${{ github.workspace }}/tools
        docker compose up -d 

    - name: Compile documents
      run: |
        cd ${{ github.workspace }}/tools
        docker exec argo-docs-latexpdfbuilder-1 bash -c 'cd /data && chmod +x *.sh && ./compilescript.sh -a'

    - name: Commit and push changes
      #env:
        #upload_token: ${{ secrets.UPLOAD_TOKEN }}
      run: |
        ls
        mv build-output Docs

    - name: Publish artifact
      uses: actions/upload-artifact@v2
      with:
        name: Docs
        path: Docs



    - name: Download Facing Repo
      uses: actions/checkout@v2
      with:
        repository: Rikicavaz77/prova_build_docker
        token: ${{ secrets.UPLOAD_TOKEN }}

    - name: Commit changes
      run: |
        git config user.name github-actions
        git config user.email riccardo.cavalli@studenti.unipd.it
        git add .
        git commit -m "[BOT] Aggiornamento documentazione"
        git push
            
    - name: Stop Docker Compose
      run: |
        cd ${{ github.workspace }}/tools
        docker compose stop
