name: Build and Stop Docker Compose

on:
  push:
    branches:
      - main
      
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Start containers
      run: |
        cd ${{ github.workspace }}/tools
        docker compose up -d 

    - name: Compile documents
      run: |
        cd ${{ github.workspace }}/tools
        docker exec argo-docs-latexpdfbuilder-1 bash -c 'cd /data && chmod +x *.sh && ./compilescript.sh -a'

    - name: Commit and push changes
      #env:
        #upload_token: ${{ secrets.UPLOAD_TOKEN }}
      run: |
        git config --local user.name 'bot'
        git config --local user.email 'riccardo.cavalli@studenti.unipd.it'
        git remote add origin https://github.com/Rikicavaz77/prova_build_docker.git
        git remote
        ls
        mv build-output Docs
        git add .
        git commit -m "Compile LaTeX files and move PDFs"
        git push -u origin
    
    - name: Publish artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Documentazione
        path: |
          build
            
    - name: Stop Docker Compose
      run: |
        cd ${{ github.workspace }}/tools
        docker compose stop
