name: Build and Stop Docker Compose

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Parent Folder
      continue-on-error: true
      run: |
        mkdir -p ChatSQL
        cp -r Logo ChatSQL
        cp -r tools ChatSQL

    - name: Upload combined artifact
      uses: actions/upload-artifact@v4
      with:
        name: combined-artifact
        path: ChatSQL/
